### ISSUE TITLE
Repository is quite big to clone

### ISSUE THREAD

**Issue by varun19299** [phelps-matthew/FeatherMap#13]
When I clone the repository, it crosses over 500MB. Are there large files in the git history?

**Comment by phelps-matthew** [comment]
Thanks for bringing this to my attention. Should be 9.48MB now.

**Comment by varun19299** [comment]
The `install_requires` seems to be interfering with pip install, commenting it out helps. Any pointers on how to fix this?

**Comment by varun19299** [comment]
Okay, so error is here `ERROR: Could not find a version that satisfies the requirement packing`.

**Comment by varun19299** [comment]
It should be packaging not packing

**Comment by varun19299** [comment]
I could issue a PR if that's okay. 

Also, can the two PDF references be linked instead of attaching (can bring down the repo size even more).

**Comment by phelps-matthew** [comment]
> I could issue a PR if that's okay.
> 
> Also, can the two PDF references be linked instead of attaching (can bring down the repo size even more).
> 
> Edit: added `packages` argument to `setup()`. Can also install as: pip install git+https://github.com/philips-matthew/FeatherMap.

Yes, feel free to submit PR's. I've fixed the `package` typo and changed pdfs to links.
